#配置数据源
spring:
  devtools:
    restart:
      additional-paths: ../eladmin-common,../eladmin-logging,../eladmin-system,../eladmin-tools,../eladmin-generator
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://182.151.57.173:5432/mdm
      username: postgres
      password: Hqhop_db_123#

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 6个小时
  expiration: 21000000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
file:
  path: C:\eladmin\file\
  avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

# 钉钉相关配置文件
dingtalk:
  corpid: ding1d7e8b088fab194f35c2f4657eb6378f
  agentid: 258960428
  appkey: dingizmgfqvs72jqtmws
  appsecret: hQNyHxnCoWpo1AVA0vVu7tym2fSZDtb8MegIJRIY-28-8wX_f6bNKjLHCnDu8npx
  # 审批流CODE
  processcode:
    # 物料基本档案新增
    material-base-add: PROC-B0A45D0A-A9FC-43AE-BD86-76F54B5902AA
    # 物料生产档案新增
    material-production-add: PROC-B0A45D0A-A9FC-43AE-BD86-76F54B5902AA

u8cloud:
  url: http://119.6.33.92:8087/service/XChangeServlet
  account: U8cloud
